name: flutter_scaler_example
description: "Example application for the flutter_scaler package."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_adaptive_scaler:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile.png
    - assets/images/banner.png

  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
